# Generated by Django 4.0.4 on 2022-04-29 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightAlertRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('layover_limit', models.IntegerField()),
                ('layover_duration_limit', models.DurationField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlightAlertOrigin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airport_code', models.CharField(max_length=3)),
                ('flight_alert_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_scanner.flightalertrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FlightAlertDestination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination_type', models.CharField(choices=[('Airport', 'Airport'), ('City', 'City'), ('State', 'State'), ('Country', 'Country')], max_length=10)),
                ('destination_name', models.CharField(max_length=250)),
                ('flight_alert_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_scanner.flightalertrequest')),
            ],
        ),
    ]
