# Generated by Django 4.0.4 on 2022-05-10 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=250)),
                ('flight_origin', models.CharField(max_length=4)),
                ('flight_destination', models.CharField(max_length=4)),
                ('airliner_code', models.CharField(max_length=15)),
                ('flight_itinerary', models.JSONField()),
            ],
        ),
        migrations.AddField(
            model_name='flightalertrequest',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flightalertrequest',
            name='max_days_at_destination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightalertrequest',
            name='min_days_at_destination',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FlightSearchResultPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date', models.DateField()),
                ('flight_search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_scanner.flightsearchresult')),
            ],
        ),
        migrations.AddField(
            model_name='flightsearchresult',
            name='flight_alert_request',
            field=models.ManyToManyField(to='flight_scanner.flightalertrequest'),
        ),
    ]
