# Generated by Django 4.0.4 on 2022-05-02 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_scanner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightalertrequest',
            name='adults',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flightalertrequest',
            name='max_days_at_destination',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='flightalertrequest',
            name='min_days_at_destination',
            field=models.IntegerField(default=0),
        ),
    ]
