# Generated by Django 4.0.4 on 2022-05-10 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_scanner', '0002_flightsearchresult_flightalertrequest_adults_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightsearchresult',
            old_name='flight_alert_request',
            new_name='flight_alert_requests',
        ),
    ]
