# Generated by Django 4.0.4 on 2022-05-09 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight_scanner', '0002_flightalertrequest_adults_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlightSearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(max_length=250)),
                ('flight_origin', models.CharField(max_length=4)),
                ('flight_destination', models.CharField(max_length=4)),
                ('airliner_code', models.CharField(max_length=15)),
                ('flight_itinerary', models.JSONField()),
                ('flight_alert_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_scanner.flightalertrequest')),
            ],
        ),
        migrations.CreateModel(
            name='FlightSearchResultPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('leave_date', models.DateField()),
                ('return_date', models.DateField()),
                ('flight_search_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flight_scanner.flightsearchresult')),
            ],
        ),
    ]
