# Generated by Django 4.0.4 on 2022-05-09 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flight_scanner', '0003_flightsearchresult_flightsearchresultpricehistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightsearchresultpricehistory',
            old_name='leave_date',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='flightsearchresultpricehistory',
            name='return_date',
        ),
    ]
